import { useEffect, useState } from "react";
import TempusLogo from "./imports/Group9";
import SiteFooter from "./SiteFooter";

type Position = { id: number; title: string; department: string; location: string; model: string; about: string; responsibilities: string[]; requirements: string[]; nice_to_have: string[]; benefits: string[] };

const positions: Position[] = [
  { id: 1, title: "Designer de Produto", department: "Design", location: "São Paulo, SP", model: "Híbrido", about: "Uma oportunidade para participar do desenvolvimento de produtos que unem conforto, proporção e experiência de uso.", responsibilities: ["Apoiar a pesquisa e o desenvolvimento de novos produtos.", "Traduzir conceitos em materiais de apresentação e especificação.", "Trabalhar em diálogo com design, engenharia e produção."], requirements: ["Formação em Design de Produto ou área relacionada.", "Domínio de ferramentas de modelagem e apresentação.", "Olhar atento para proporção, materialidade e detalhe."], nice_to_have: ["Experiência com mobiliário ou interiores.", "Conhecimento de processos industriais."], benefits: ["Ambiente colaborativo", "Desenvolvimento profissional", "Benefícios compatíveis com a posição"] },
  { id: 2, title: "Analista Comercial", department: "Comercial", location: "São Paulo, SP", model: "Presencial", about: "Uma posição próxima da rede de parceiros e dos projetos que levam a Tempus a diferentes regiões.", responsibilities: ["Acompanhar a rotina comercial e os parceiros da marca.", "Organizar informações para suporte à equipe.", "Contribuir para uma experiência de atendimento precisa."], requirements: ["Vivência em rotinas comerciais.", "Boa comunicação escrita e verbal.", "Organização e atenção aos detalhes."], nice_to_have: ["Experiência com mobiliário, varejo ou arquitetura."], benefits: ["Ambiente colaborativo", "Desenvolvimento profissional", "Benefícios compatíveis com a posição"] },
];

const principles = [["01", "Curiosidade", "Buscamos entender antes de criar."], ["02", "Precisão", "Cuidamos dos detalhes que fazem diferença."], ["03", "Colaboração", "Boas soluções são construídas em conjunto."], ["04", "Responsabilidade", "Cada decisão tem impacto no produto e na experiência."]];
const teamPhotos = ["https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1600&h=1100&fit=crop&auto=format", "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1600&h=1100&fit=crop&auto=format", "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1600&h=1100&fit=crop&auto=format"];

export default function CareersPage() {
  const [headerScrolled, setHeaderScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [selectedPosition, setSelectedPosition] = useState<Position | null>(null);
  const [teamIndex, setTeamIndex] = useState(0);

  useEffect(() => { const onScroll = () => setHeaderScrolled(window.scrollY > 12); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setSelectedPosition(null); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  const shiftTeam = (direction: number) => setTeamIndex((index) => (index + direction + teamPhotos.length) % teamPhotos.length);

  return <main className="page-shell careers-page">
    <header className={headerScrolled ? "minimal-header is-scrolled" : "minimal-header"}><a className="brand brand-logo" href="/" aria-label="Tempus, início"><TempusLogo /></a><nav className={menuOpen ? "minimal-nav is-open" : "minimal-nav"} aria-label="Navegação principal"><a href="/categorias/reclinaveis" onClick={() => setMenuOpen(false)}>Produtos</a><a href="/sobre" onClick={() => setMenuOpen(false)}>Sobre nós</a><a href="/conteudos" onClick={() => setMenuOpen(false)}>Conteúdos</a><a href="/blocos-3d" onClick={() => setMenuOpen(false)}>Blocos 3D</a><a href="/representantes" onClick={() => setMenuOpen(false)}>Representantes</a><a href="/seja-representante" onClick={() => setMenuOpen(false)}>Seja representante</a><a href="/parceiros" onClick={() => setMenuOpen(false)}>Parceiros</a><a href="/carreiras" onClick={() => setMenuOpen(false)}>Carreiras</a></nav><a className="quiet-cta" href="https://wa.me/" target="_blank" rel="noreferrer">Fale conosco <span>↗</span></a><button className="menu-toggle" type="button" aria-label="Abrir menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button></header>

    <section className="careers-hero" aria-labelledby="careers-title"><img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=2400&h=1500&fit=crop&auto=format" alt="Equipe colaborando em ambiente de trabalho criativo" /><div><p className="editorial-eyebrow">Carreiras</p><h1 id="careers-title">Faça parte do que estamos <em>construindo.</em></h1><p>Na Tempus, design, tecnologia e pessoas trabalham juntas para criar novas formas de viver.</p><a className="editorial-action editorial-action--light" href="#oportunidades">Ver oportunidades <span>↗</span></a></div></section>

    <section className="careers-statement" aria-labelledby="statement-title"><p className="editorial-number">01 / Pessoas e propósito</p><h2 id="statement-title">Grandes produtos começam com<br /><em>grandes pessoas.</em></h2><p>A Tempus é construída por profissionais de diferentes disciplinas, que trabalham juntos em design, tecnologia, produção, comercial e operações para transformar cuidado em experiência.</p></section>

    <section className="careers-principles" aria-labelledby="principles-title"><header><p className="editorial-eyebrow editorial-eyebrow--dark">Como trabalhamos</p><h2 id="principles-title">Diferentes perspectivas.<br /><em>Um mesmo cuidado.</em></h2></header><div>{principles.map(([number, title, copy]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>

    <section className="careers-positions" id="oportunidades" aria-labelledby="positions-title"><header><p className="editorial-eyebrow editorial-eyebrow--dark">Oportunidades</p><h2 id="positions-title">Talvez o próximo lugar<br /><em>seja aqui.</em></h2></header><div className="positions-list">{positions.length ? positions.map((position, index) => <button type="button" onClick={() => setSelectedPosition(position)} key={position.id}><span>{String(index + 1).padStart(2, "0")}</span><h3>{position.title}</h3><p>{position.department}</p><p>{position.location}</p><p>{position.model}</p><b>→</b></button>) : <div className="positions-empty"><p>No momento, não temos posições abertas.</p><a className="editorial-action" href="#curriculo">Envie seu currículo mesmo assim <span>↗</span></a></div>}</div></section>

    <section className="careers-team" aria-labelledby="team-title"><header><p className="editorial-eyebrow editorial-eyebrow--dark">Pessoas</p><h2 id="team-title">Pessoas fazem a <em>Tempus.</em></h2><p>Uma equipe multidisciplinar, próxima e comprometida com cada etapa do que fazemos.</p><div className="careers-team-controls"><button type="button" onClick={() => shiftTeam(-1)} aria-label="Imagem anterior">←</button><span>{String(teamIndex + 1).padStart(2, "0")} / {String(teamPhotos.length).padStart(2, "0")}</span><button type="button" onClick={() => shiftTeam(1)} aria-label="Próxima imagem">→</button></div></header><div className="careers-team-gallery" style={{ transform: `translateX(-${teamIndex * 68}%)` }}>{teamPhotos.map((photo, index) => <img src={photo} alt="Equipe Tempus trabalhando em conjunto" key={photo} />)}</div></section>

    <section className="careers-closing" id="curriculo" aria-labelledby="closing-title"><img src="https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=2400&h=1500&fit=crop&auto=format" alt="Equipe em um espaço de trabalho contemporâneo" /><div><h2 id="closing-title">Vamos construir o próximo capítulo <em>juntos.</em></h2><p>Envie seu currículo e conte um pouco sobre você.</p><a className="editorial-action editorial-action--light" href="mailto:carreiras@tempusdecor.com.br?subject=Quero%20fazer%20parte%20da%20Tempus">Quero fazer parte <span>↗</span></a></div></section>
    <SiteFooter />

    {selectedPosition && <div className="career-modal-backdrop" onMouseDown={() => setSelectedPosition(null)} role="presentation"><section className="career-modal" onMouseDown={(event) => event.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="career-modal-title"><button type="button" className="career-modal-close" onClick={() => setSelectedPosition(null)} aria-label="Fechar vaga">×</button><p className="editorial-eyebrow editorial-eyebrow--dark">{selectedPosition.department} / {selectedPosition.location} / {selectedPosition.model}</p><h2 id="career-modal-title">{selectedPosition.title}</h2><p className="career-modal-about">{selectedPosition.about}</p>{[["Responsabilidades", selectedPosition.responsibilities], ["Requisitos", selectedPosition.requirements], ["Diferenciais", selectedPosition.nice_to_have], ["Benefícios", selectedPosition.benefits]].map(([title, items]) => <div className="career-modal-list" key={title as string}><h3>{title as string}</h3><ul>{(items as string[]).map((item) => <li key={item}>{item}</li>)}</ul></div>)}<a className="editorial-action" href={`mailto:carreiras@tempusdecor.com.br?subject=${encodeURIComponent(selectedPosition.title)}`}>Candidatar-se <span>↗</span></a></section></div>}
  </main>;
}
