import { useMemo, useState } from "react";
const colors = [
  ["--page", "Page", "#f3f2ed", "rgb(243, 242, 237)", "hsl(45 14% 94%)", "Fundo principal e navegação"],
  ["--paper", "Paper", "#f8f7f3", "rgb(248, 247, 243)", "hsl(48 26% 96%)", "Superfícies claras"],
  ["--ink", "Ink", "#171815", "rgb(23, 24, 21)", "hsl(75 7% 9%)", "Texto, ícones e bordas opacas"],
  ["--muted", "Muted", "#77786f", "rgb(119, 120, 111)", "hsl(72 4% 45%)", "Texto secundário e labels"],
  ["--dark", "Dark", "#20211e", "rgb(32, 33, 30)", "hsl(90 5% 12%)", "Blocos escuros e footer"],
  ["--lime", "CTA fill", "#d8d7d1", "rgb(216, 215, 209)", "hsl(43 8% 83%)", "Círculo de CTA; token mantido com nome legado"],
  ["--line", "Line", "rgba(23,24,21,.2)", "rgba(23,24,21,0.2)", "Não identificado", "Divisores e bordas"],
];
const typeRows = [
  ["Display / H1", "Manrope", "500", "clamp(58–112px)", "0.96–1.01", "−0.047em a −0.064em"],
  ["H2 editorial", "Manrope", "500", "clamp(40–78px)", "1.01", "−0.047em"],
  ["H3 de produto", "Manrope", "500", "28–30px", "Não identificado", "Normal"],
  ["Body", "Manrope", "400", "16px", "1.5–1.75", "Normal"],
  ["Body compacto", "Manrope", "400", "11–14px", "1.4–1.7", "Normal"],
  ["Label / eyebrow", "Manrope", "400/600", "9–10px", "Não identificado", "+0.10–0.14em, uppercase"],
  ["Nav / CTA", "Manrope", "400/700", "12–13px", "Não identificado", "Normal"],
];
const spacing = ["4vw", "7%", "8%", "18px", "20px", "22px", "24px", "28px", "30px", "34px", "44px", "54px", "70px", "82px", "120px", "clamp(70px, 8vw, 120px)", "clamp(100px, 12vw, 170px)"];
const components = [
  ["Ação editorial", "Link de texto com sublinhado de 1px; variante clara em fundos escuros.", "Default / light", "Hover: não identificado de forma consistente"],
  ["Quiet CTA", "CTA do header: texto + círculo de 34px com seta.", "34 × 34px / radius 50%", "Preenchimento usa --lime"],
  ["Header mínimo", "Grid com marca, navegação centrada e CTA; menu se torna colunar.", "82px desktop · 72px mobile", "Sticky; blur apenas onde declarado"],
  ["Card de produto", "Imagem, legenda, índice e link; grid editorial.", "Sem radius · divisores 1px", "Imagem: scale 1.025 em hover"],
  ["Campo de formulário", "Label uppercase, campo sem caixa e divisor inferior.", "Sem radius · fundo transparente", "Required nativo; erro visual não identificado"],
  ["Filtro / região", "Botões e selects presentes no localizador de representantes.", "Estado selecionado (.is-active)", "Demais estados não identificados"],
  ["Accordion de representante", "Linha expansível com detalhes de contato.", "Default / .is-expanded", "Ícone alterna + e −"],
];

function Swatch({ color, label }: { color: string; label: string }) { return <div className="ds-swatch"><i style={{ background: color }} /><b>{label}</b></div>; }

const searchIndex = [
  ["colors", "Colors", "#foundations", "--page #f3f2ed --paper #f8f7f3 --ink #171815 --muted #77786f --dark #20211e --line"],
  ["typography", "Typography", "#type", "Manrope heading display h1 h2 body label"],
  ["spacing", "Spacing", "#spacing", "padding gap section 20px 24px 70px 120px"],
  ["grid", "Grid & breakpoints", "#grid", "desktop mobile 1000px 900px 720px 620px"],
  ["buttons", "Buttons & CTAs", "#components", "quiet cta editorial action circle 34px"],
  ["inputs", "Inputs & forms", "#components", "input select textarea field form"],
  ["cards", "Cards & media", "#components", "product card image hover scale"],
  ["responsive", "Responsive audit", "#patterns", "mobile tablet desktop responsive"],
  ["inconsistencies", "System inconsistencies", "#patterns", "inconsistent focus radius lime breakpoints"],
  ["technical", "Technical source", "#technical", "css variables source inferred"],
];

export default function DesignSystemPage() {
  const [query, setQuery] = useState("");
  const [copied, setCopied] = useState("");
  const [preview, setPreview] = useState("default");
  const [viewport, setViewport] = useState("desktop");
  const matches = useMemo(() => { const needle = query.trim().toLowerCase(); return needle ? searchIndex.filter((item) => item.join(" ").toLowerCase().includes(needle)) : []; }, [query]);
  const copy = async (value: string) => { await navigator.clipboard?.writeText(value); setCopied(value); window.setTimeout(() => setCopied(""), 1600); };
  return <main className="ds-page"><aside className="ds-sidebar"><a className="brand" href="/">TEMPOS <span>/ system</span></a><label className="ds-search"><span>Busca global</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="button, #171815, 32px" /></label>{matches.length > 0 && <div className="ds-search-results">{matches.map(([, name, link]) => <a key={name} href={link}>{name}<span>↘</span></a>)}</div>}<nav><b>Foundations</b><a href="#foundations">Colors</a><a href="#type">Typography</a><a href="#spacing">Spacing</a><a href="#grid">Grid & breakpoints</a><b>Components</b><a href="#components">Actions & navigation</a><a href="#components">Fields & forms</a><a href="#components">Cards & media</a><b>Audit</b><a href="#patterns">Patterns & responsive</a><a href="#patterns">Inconsistencies</a><a href="#technical">Technical source</a></nav><small>Source-bound documentation<br />{copied ? `Copiado: ${copied}` : "Valores com ação de cópia"}</small></aside><div className="ds-canvas">
    <header className="ds-top"><span>Forensic reconstruction / code audit</span><nav><a href="#foundations">Foundations</a><a href="#components">Components</a><a href="#technical">Technical source</a></nav><span>11 rotas auditadas</span></header>
    <section className="ds-intro"><p className="editorial-eyebrow editorial-eyebrow--dark">Design System / extração v1.0</p><h1>O sistema como ele <em>existe.</em></h1><p>Referência técnica e visual extraída das rotas atuais do site Tempos. Valores declarados em código são exibidos como diretos; leituras por recorrência são sinalizadas como <b>Inferido</b>.</p><dl><div><dt>Rotas auditadas</dt><dd>11</dd></div><div><dt>Fonte identificada</dt><dd>Manrope</dd></div><div><dt>Radius de sistema</dt><dd>0px / 50%</dd></div><div><dt>Sombras</dt><dd>Não identificado</dd></div></dl></section>

    <section className="ds-section" id="foundations"><div className="ds-section-title"><p>01 / Foundations</p><h2>Tokens<br /><em>encontrados.</em></h2></div><div className="ds-section-body">
      <h3>Colors <small>Direto: :root em src/index.css · frequência: global / alta</small></h3><div className="ds-color-grid">{colors.map(([token, name, hex, rgb, hsl, purpose]) => <article key={token}><Swatch color={hex.startsWith("rgba") ? "rgba(23,24,21,.2)" : hex} label={name} /><div className="ds-value"><code>{token}</code><button type="button" onClick={() => copy(`${token}: ${hex}`)}>Copy</button></div><p><b>{hex}</b><br />{rgb}<br />{hsl}</p><small>{purpose}</small></article>)}</div>
      <div className="ds-subgrid" id="type"><div><h3>Typography <small>Direto / inferido por ocorrências</small></h3><div className="ds-type-sample"><p className="ds-display">Design para<br /><em>viver melhor.</em></p><p className="ds-body">Manrope é a única família carregada por Google Fonts e está vinculada aos tokens <code>--font-display</code> e <code>--font-sans</code>.</p></div></div><div className="ds-type-table">{typeRows.map((row) => <div key={row[0]}>{row.map((cell, i) => <span key={i}>{cell}</span>)}</div>)}</div></div>
      <div className="ds-subgrid" id="spacing"><div><h3>Spacing <small>Valores recorrentes / Direto</small></h3><div className="ds-spacing">{spacing.map((value, i) => <div key={value}><i style={{ width: `${Math.min(100, 8 + i * 6)}%` }} /><span>{value}</span></div>)}</div></div><div><h3>Radius, borders & shadows</h3><div className="ds-foundation-pairs"><article><i className="ds-radius-none" /><b>Radius none</b><span>0px — cartões, imagens e campos</span></article><article><i className="ds-radius-full" /><b>Radius full</b><span>50% — círculo de CTA, 34 × 34px</span></article><article><i className="ds-border" /><b>Divider</b><span>1px solid var(--line)</span></article><article><i className="ds-shadow" /><b>Shadows</b><span>Não identificado</span></article></div></div></div>
      <h3 id="grid">Grid & breakpoints <small>Direto: media queries globais</small></h3><div className="ds-grid-showcase"><div className="ds-grid-3"><i /><i /><i /></div><dl><div><dt>Desktop base</dt><dd>Header: 220px / 1fr / 180px</dd></div><div><dt>≤ 1000px</dt><dd>Nav colapsa; grids passam a 1–2 colunas</dd></div><div><dt>≤ 900px</dt><dd>Grids específicos de páginas viram 1 coluna</dd></div><div><dt>≤ 720px</dt><dd>Header 72px; seções e hero compactam</dd></div><div><dt>≤ 620px</dt><dd>Formulários passam a 1 coluna</dd></div></dl></div>
    </div></section>

    <section className="ds-section ds-section-dark" id="components"><div className="ds-section-title"><p>02 / Components</p><h2>Peças<br /><em>reutilizadas.</em></h2></div><div className="ds-section-body">
      <div className="ds-explorer"><div><p className="editorial-eyebrow">Interactive specimen / only existing variants</p><h3>Editorial action</h3><p>Alterna entre os dois tratamentos localizados: padrão em fundo claro e <code>editorial-action--light</code> em fundo escuro.</p></div><div className={`ds-explorer-preview is-${preview}`}><a className={preview === "light" ? "editorial-action editorial-action--light" : "editorial-action"} href="#components">Quero representar a Tempos <span>↗</span></a></div><div className="ds-controls"><label>Variant<select value={preview} onChange={(event) => setPreview(event.target.value)}><option value="default">Default</option><option value="light">Light</option></select></label><label>Viewport<select value={viewport} onChange={(event) => setViewport(event.target.value)}><option value="desktop">Desktop</option><option value="tablet">Tablet</option><option value="mobile">Mobile</option></select></label><span>Visual: {viewport}</span></div></div>
      <div className="ds-component-grid">{components.map(([name, description, anatomy, state]) => <article key={name}><div className="ds-component-visual">{name === "Quiet CTA" ? <button className="quiet-cta">Contato <span>↗</span></button> : name === "Campo de formulário" ? <label className="ds-input"><span>Nome</span><input placeholder="Seu nome" /></label> : name === "Accordion de representante" ? <div className="ds-accordion"><span>01</span><b>Atendimento regional</b><i>+</i></div> : name === "Card de produto" ? <div className="ds-card"><div /><span>01</span><b>Poltrona</b><i>↗</i></div> : <a className="editorial-action editorial-action--light" href="#components">{name} <span>↗</span></a>}</div><h3>{name}</h3><p>{description}</p><dl><div><dt>Anatomia / medida</dt><dd>{anatomy}</dd></div><div><dt>Estados</dt><dd>{state}</dd></div></dl></article>)}</div>
      <div className="ds-content-specimens"><article><p className="editorial-eyebrow">Content / label</p><h2>Hierarquia<br /><em>editorial.</em></h2><p>Corpo em 16px com texto secundário em <code>--muted</code>. Links usam cor herdada e ausência de sublinhado global; CTAs recebem borda inferior.</p><ul><li>Listas usam marcadores ou numeração conforme contexto</li><li>Badges, tooltips, toasts e modais: Não identificado</li><li>Tabelas: Não identificado</li></ul></article><article className="ds-media"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=900&h=720&fit=crop&auto=format" alt="Exemplo de tratamento de mídia" /><div><b>Media treatment</b><span>object-fit: cover ou contain</span><span>Radius: 0px</span><span>Hover: scale 1.025 / 1.03 em cards</span><span>Overlay: gradiente preto em legendas</span></div></article></div>
    </div></section>

    <section className="ds-section"><div className="ds-section-title"><p>03 / Patterns</p><h2>Composição e<br /><em>movimento.</em></h2></div><div className="ds-section-body"><div className="ds-responsive-toggle"><span>Responsive preview — regra documentada, não simulação de runtime</span>{["mobile", "tablet", "desktop"].map((name) => <button type="button" className={viewport === name ? "is-active" : ""} onClick={() => setViewport(name)} key={name}>{name}</button>)}</div><div className={`ds-layout-preview is-${viewport}`}><i /><i /><i /><b>{viewport}: {viewport === "mobile" ? "1 coluna" : viewport === "tablet" ? "2 colunas" : "grid editorial"}</b></div><div className="ds-patterns" id="patterns"><article><span>01</span><h3>Editorial split</h3><p>Blocos em grid com divisores finos, copy lateral e mídia em escala ampla. Encontrado em home, categoria, parceiros e páginas comerciais.</p></article><article><span>02</span><h3>Full viewport</h3><p>Heróis e grandes seções operam entre 680–900px ou 100vh, com redução em mobile. Inferido por regras recorrentes.</p></article><article><span>03</span><h3>Motion</h3><p><code>transform .4s</code> a <code>.45s</code> em imagens de cards; links do footer: <code>color .2s ease, opacity .2s ease</code>. Scroll suave global. Outros motion: Não identificado.</p></article></div><h3>Inconsistências encontradas</h3><div className="ds-issues"><article><b>Nome do token de CTA</b><p><code>--lime</code> atualmente resolve para <code>#d8d7d1</code>, um neutro. O nome não descreve o valor atual.</p><small>Origem provável: alteração de paleta sem renomear token.</small></article><article><b>Escala tipográfica de H1</b><p>Há clamps de 62–92px, 58–112px e 55–100px em páginas distintas.</p><small>Uso: home, parceiros e recrutamento.</small></article><article><b>Breakpoints</b><p>Regras globais em 1000px e 720px, com páginas usando 900px e 620px.</p><small>Não há uma escala única de breakpoint declarada.</small></article><article><b>Estados de foco / erro</b><p>Inputs removem <code>outline</code>; estilos explícitos de foco, erro, disabled e loading não foram localizados.</p><small>Impacto: documentação não deve inferir esses estados.</small></article></div></div></section>

    <section className="ds-tech" id="technical"><div><p className="editorial-eyebrow">Technical reference</p><h2>Notas de <em>extração.</em></h2></div><div><h3>Design system health</h3><div className="ds-health"><span><b>Tokens</b> Mostly consistent</span><span><b>Typography</b> Mostly consistent</span><span><b>Spacing</b> Inconsistent</span><span><b>Color</b> Mostly consistent</span><span><b>Components</b> Inconsistent</span><span><b>Responsive</b> Inconsistent</span></div><dl><div><dt>Identificado diretamente</dt><dd>Variáveis em <code>:root</code>, import Google Fonts, medidas em CSS, media queries, transições, rotas e classes de componentes.</dd></div><div><dt>Inferido</dt><dd>Frequência dos padrões editoriais, hierarquia dos textos e escala de spacing recorrente.</dd></div><div><dt>Não identificado</dt><dd>Biblioteca de ícones, sombras, tokens semânticos de feedback, breadcrumbs, modais, tooltips, tabs, radio/checkbox, loading e estados visuais completos.</dd></div><div><dt>Arquivos analisados</dt><dd><code>src/index.css</code>; todas as páginas <code>src/*Page.tsx</code>; <code>src/SiteFooter.tsx</code>; <code>src/routes.tsx</code>; <code>package.json</code>.</dd></div><div><dt>Limitações</dt><dd>A auditoria é baseada no código disponível no projeto e não mede valores calculados em runtime ou interações não implementadas.</dd></div></dl></div></section>
  </div></main>;
}
