export type JournalArticle = { id: number; slug: string; category: string; title: string; description: string; date: string; image: string; readingTime: string };

export const journalArticles: JournalArticle[] = [
  { id: 1, slug: "mobiliario-transforma-espaco", category: "Arquitetura", title: "Como o mobiliário transforma a percepção de um espaço", description: "Uma reflexão sobre proporção, escala e a relação entre objetos e arquitetura.", date: "12.08.2026", image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1500&h=1000&fit=crop&auto=format", readingTime: "5 min de leitura" },
  { id: 2, slug: "conforto-como-parte-do-projeto", category: "Design", title: "O conforto como parte do projeto", description: "Como tecnologia e desenho podem trabalhar juntos para criar novas experiências.", date: "05.08.2026", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1500&h=1000&fit=crop&auto=format", readingTime: "6 min de leitura" },
  { id: 3, slug: "tecnologia-desaparece-no-ambiente", category: "Tecnologia", title: "Quando tecnologia desaparece no ambiente", description: "Como sistemas inteligentes podem melhorar uma experiência sem dominar o espaço.", date: "28.07.2026", image: "https://images.unsplash.com/photo-1599933345241-2d01fe8d06ec?w=1500&h=1000&fit=crop&auto=format", readingTime: "4 min de leitura" },
  { id: 4, slug: "casa-lugar-de-permanencia", category: "Interiores", title: "A casa como lugar de permanência", description: "Ambientes que acolhem o tempo, o cotidiano e as pequenas pausas.", date: "18.07.2026", image: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=1500&h=1000&fit=crop&auto=format", readingTime: "5 min de leitura" },
  { id: 5, slug: "materia-luz-e-silencio", category: "Inspiração", title: "Matéria, luz e silêncio", description: "Referências para pensar interiores com mais intenção e menos ruído.", date: "10.07.2026", image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1500&h=1000&fit=crop&auto=format", readingTime: "4 min de leitura" },
  { id: 6, slug: "o-que-permanece-em-cada-detalhe", category: "Tempus", title: "O que permanece em cada detalhe", description: "Uma conversa sobre cuidado, processo e as decisões por trás da Tempus.", date: "02.07.2026", image: "https://images.unsplash.com/photo-1564078516393-cf04bd966897?w=1500&h=1000&fit=crop&auto=format", readingTime: "5 min de leitura" },
  { id: 7, slug: "mobiliario-parte-da-arquitetura", category: "Arquitetura", title: "Quando o mobiliário passa a fazer parte da arquitetura", description: "Como proporção, escala e matéria transformam a relação entre objeto e espaço.", date: "24.06.2026", image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?w=1200&h=900&fit=crop&auto=format", readingTime: "5 min de leitura" },
  { id: 8, slug: "menos-excesso-mais-intencao", category: "Design", title: "Menos excesso. Mais intenção.", description: "O papel da simplicidade na criação de produtos duradouros.", date: "17.06.2026", image: "https://images.unsplash.com/photo-1493666438817-866a91353ca9?w=1200&h=900&fit=crop&auto=format", readingTime: "4 min de leitura" },
  { id: 9, slug: "tecnologia-que-nao-precisa-aparecer", category: "Tecnologia", title: "Tecnologia que não precisa aparecer", description: "Como soluções inteligentes podem melhorar o conforto sem interferir na estética.", date: "09.06.2026", image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=1200&h=900&fit=crop&auto=format", readingTime: "5 min de leitura" },
  { id: 10, slug: "espaco-entre-uma-peca-e-outra", category: "Interiores", title: "O espaço entre uma peça e outra", description: "Por que o vazio também é parte fundamental de um ambiente.", date: "01.06.2026", image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&h=900&fit=crop&auto=format", readingTime: "4 min de leitura" },
  { id: 11, slug: "materiais-que-envelhecem-bem", category: "Inspiração", title: "Materiais que envelhecem bem", description: "Uma investigação sobre matéria, textura e permanência.", date: "25.05.2026", image: "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=1200&h=900&fit=crop&auto=format", readingTime: "6 min de leitura" },
  { id: 12, slug: "projetar-para-o-cotidiano", category: "Design", title: "Projetar para o cotidiano", description: "Como o uso real transforma as decisões de design.", date: "18.05.2026", image: "https://images.unsplash.com/photo-1617104678098-de229db51175?w=1200&h=900&fit=crop&auto=format", readingTime: "5 min de leitura" },
];
export const latestArticles = journalArticles.slice(0, 6);
export const exploreArticles = journalArticles.slice(6);
export const categories = ["Todos", "Design", "Arquitetura", "Interiores", "Tecnologia", "Inspiração", "Tempus"];
